"use client";

import { useState } from "react";
import Link from "next/link";
import { ExternalLink, Shield, Bot, Heart, ChevronUp, ChevronDown, MessageSquare } from "lucide-react";
import { useSettings } from "@/lib/SettingsContext";

// Googleフォームのリンク
const CONTACT_FORM_URL = "https://docs.google.com/forms/d/e/1FAIpQLSe5lAyyv91mnj68KwORhocKHcFjqgAkVSXaUczieyIOtueFOQ/viewform?usp=publish-editor";

export default function Footer() {
  const { t } = useSettings();
  const [isExpanded, setIsExpanded] = useState(false);

  return (
    <footer className="footer-container">
      {/* Toggle Button */}
      <button
        onClick={() => setIsExpanded(!isExpanded)}
        className="footer-toggle"
        aria-label={isExpanded ? "Close footer details" : "Open footer details"}
      >
        <Shield className="w-3.5 h-3.5 text-neon-blue/60" />
        <span className="text-[11px] text-foreground/40 font-[var(--font-orbitron)] tracking-wider">
          {t("利用規約・免責事項", "TERMS & DISCLAIMER")}
        </span>
        {isExpanded ? (
          <ChevronDown className="w-3.5 h-3.5 text-foreground/30" />
        ) : (
          <ChevronUp className="w-3.5 h-3.5 text-foreground/30" />
        )}
      </button>

      {/* Expandable Content */}
      <div
        className={`footer-expandable ${isExpanded ? "footer-expanded" : ""}`}
      >
        <div className="footer-content">
          {/* Section Grid */}
          <div className="footer-grid">
            {/* About */}
            <div className="footer-section">
              <h3 className="footer-heading">
                <Bot className="w-3.5 h-3.5" />
                {t("本サービスについて", "About This Service")}
              </h3>
              <p className="footer-text">
                {t(
                  "「V-Singer Roulette」は、YouTube Data APIおよびGemini AIを活用し、歌唱活動を行うVtuberをランダムに紹介するファンプロジェクトです。",
                  '"V-Singer Roulette" is a fan project that uses the YouTube Data API and Gemini AI to randomly introduce Vtubers who engage in singing activities.'
                )}
                <br />
                {t(
                  "※自動収集の性質上、Vtuber以外のチャンネルが選出される場合や、過去に紹介したチャンネルが重複して選出される場合があります。",
                  "*Due to automated collection, non-Vtuber channels or previously introduced channels may be repeatedly selected."
                )}
              </p>
            </div>

            {/* AI Content Notice */}
            <div className="footer-section">
              <h3 className="footer-heading">
                <Bot className="w-3.5 h-3.5" />
                {t("AIによる生成コンテンツ", "AI-Generated Content")}
              </h3>
              <p className="footer-text">
                {t(
                  "紹介文・声質分析・サビの特定はGemini AIによる自動生成です。AIによる推論であり、公式な見解や事実を保証するものではありません。",
                  "Introductions, voice analysis, and chorus identification are auto-generated by Gemini AI. These are AI-driven inferences and do not guarantee official views or facts."
                )}
              </p>
            </div>

            {/* Heart System */}
            <div className="footer-section">
              <h3 className="footer-heading">
                <Heart className="w-3.5 h-3.5" />
                {t("応援システムについて", "Support System")}
              </h3>
              <p className="footer-text">
                {t(
                  "応援ハートボタンにより、次回更新までの時間を短縮できます。クリックにより個人を識別する情報が収集されることはありません。",
                  "The support heart button shortens the countdown to the next update. No personally identifiable information is collected."
                )}
              </p>
            </div>

            {/* Disclaimer */}
            <div className="footer-section">
              <h3 className="footer-heading">
                <Shield className="w-3.5 h-3.5" />
                {t("免責事項", "Disclaimer")}
              </h3>
              <p className="footer-text">
                {t(
                  "本サイトの利用により生じた損失やトラブルについて、運営者は一切の責任を負いません。動画・画像・音声の著作権は各権利所有者に属します。",
                  "The operator is not liable for any loss or trouble arising from the use of this site. Copyrights belong to their respective rights holders."
                )}
              </p>
            </div>
          </div>

          {/* Links Row */}
          <div className="footer-links">
            <a
              href="https://www.youtube.com/t/terms"
              target="_blank"
              rel="noopener noreferrer"
              className="footer-link"
            >
              <ExternalLink className="w-3 h-3" />
              {t("YouTube 利用規約", "YouTube Terms of Service")}
            </a>

            <span className="footer-link-divider">|</span>

            <a
              href="https://policies.google.com/privacy"
              target="_blank"
              rel="noopener noreferrer"
              className="footer-link"
            >
              <ExternalLink className="w-3 h-3" />
              {t("Google プライバシーポリシー", "Google Privacy Policy")}
            </a>

            <span className="footer-link-divider">|</span>

            <a
              href={CONTACT_FORM_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="footer-link footer-link-contact"
            >
              <MessageSquare className="w-3 h-3" />
              {t("お問い合わせ・削除依頼", "Contact / Takedown Request")}
            </a>
          </div>
        </div>
      </div>

      {/* Always Visible Bottom Bar */}
      <div className="footer-bottom">
        <p className="footer-copyright">
          © 2026 V-SINGER GACHA — Powered by AI
        </p>
        <p className="footer-yt-notice">
          {t(
            "本サービスはYouTube API Servicesを利用しています",
            "This service uses YouTube API Services"
          )}
        </p>
      </div>
    </footer>
  );
}
